npcgen/characters/models.py
import random


class Gender:
    MALE = "Male"
    FEMALE = "Female"
    NOT_SPECIFIED = "Not specified"


class ItemType:
    MELEE_WEAPON = "Melee Weapon"
    RANGED_WEAPON = "Ranged Weapon"
    ARMOR = "Armor"
    GEAR = "Gear"
    TOOL = "Tool"
    CONSUMABLE = "Consumable"
    TREASURE = "Treasure"
    OTHER = "Other"


class Character:
    def __init__(
        self,
        alignment_id,
        class_id,
        race_id,
        level=1,
        gender=Gender.NOT_SPECIFIED,
        name=None,
        hints=None,
        backstory=None,
        plot_hook=None,
        strength=None,
        dexterity=None,
        constitution=None,
        intelligence=None,
        wisdom=None,
        charisma=None,
        perception=None,
        armor_class=None,
        hit_points=None,
        speed=None,
        fortitude_save=None,
        reflex_save=None,
        will_save=None,
        id=None,
        alignment_name=None,
        class_name=None,
        template_id=None,
        template_name=None,
        race_name=None,
        user_id=None,
        is_template=False,
        skills=[],
        items=[],
    ):
        self.user_id = user_id

        self.template_id = template_id
        self.template_name = template_name

        self.alignment_id = alignment_id
        self.alignment_name = alignment_name

        self.class_id = class_id
        self.class_name = class_name

        self.race_id = race_id
        self.race_name = race_name

        self.name = name
        self.hints = hints
        self.backstory = backstory
        self.plot_hook = plot_hook
        self.level = level
        self.gender = gender

        # Stats
        self.strength = strength
        self.dexterity = dexterity
        self.constitution = constitution
        self.intelligence = intelligence
        self.wisdom = wisdom
        self.charisma = charisma
        self.armor_class = armor_class
        self.hit_points = hit_points
        self.speed = speed
        self.perception = perception

        # Saving Throws
        self.fortitude_save = fortitude_save
        self.reflex_save = reflex_save
        self.will_save = will_save

        self.id = id
        self.is_template = is_template

        self.skills = skills
        self.items = items

    def apply_random_modifiers(self):
        self.strength += self._get_random_modifier()
        self.dexterity += self._get_random_modifier()
        self.constitution += self._get_random_modifier()
        self.intelligence += self._get_random_modifier()
        self.wisdom += self._get_random_modifier()
        self.charisma += self._get_random_modifier()

        self.perception += self._get_random_modifier(2)
        self.armor_class += self._get_random_modifier(2)
        self.hit_points += self._get_random_modifier(10)

        self.fortitude_save += self._get_random_modifier(2)
        self.reflex_save += self._get_random_modifier(2)
        self.will_save += self._get_random_modifier(2)

        for skill in self.skills:
            skill.proficiency += self._get_random_modifier(2)

        for item in self.items:
            item.proficiency += self._get_random_modifier(2)

    def _get_random_modifier(self, range=1):
        return random.randint(-range, range)


class Item:
    def __init__(
        self,
        name,
        item_type,
        damage,
        damage_type,
        traits,
        id=None,
    ):
        self.id = id
        self.name = name
        self.item_type = item_type
        self.damage = damage
        self.damage_type = damage_type
        self.traits = traits


class CharacterItem(Item):
    def __init__(self, item, proficiency, id=None):
        super().__init__(
            name=item.name,
            item_type=item.item_type,
            damage=item.damage,
            damage_type=item.damage_type,
            traits=item.traits,
            id=item.id,
        )
        self.proficiency = proficiency


class Skill:
    def __init__(self, name, description, id=None):
        self.id = id
        self.name = name
        self.description = description


class CharacterSkill(Skill):
    def __init__(self, skill, proficiency, id=None):
        super().__init__(
            name=skill.name,
            description=skill.description,
            id=skill.id,
        )
        self.proficiency = proficiency


class Option:
    def __init__(self, name, description=None, id=None):
        self.id = id
        self.name = name
        self.description = description

npcgen/characters/forms.py
import random

from flask_wtf import FlaskForm
from wtforms import SelectField, TextAreaField
from wtforms.validators import Length, Optional


class CharacterForm(FlaskForm):
    game_system = SelectField(
        "Game system",
        validators=[],
        choices=[
            ("Pathfinder 2e"),
        ],
        default="Pathfinder 2e",
        render_kw={"disabled": ""},
    )
    hints = TextAreaField(
        "Hints",
        validators=[Optional(), Length(max=200)],
        description=(
            "Character's personality traits, ideals, bonds, and flaws. "
            "These are used to generate the character's background and name."
        ),
    )
    alignment_id = SelectField(
        "Alignment",
        validators=[],
    )
    template_id = SelectField(
        "Template",
        validators=[Optional()],
        description=(
            "Template determines the character's level and stats "
            "distribution, as well as the items and skills they have."
        ),
    )
    class_id = SelectField(
        "Class",
        validators=[Optional()],
    )
    race_id = SelectField(
        "Race",
        validators=[Optional()],
    )

    def get_choice_or_random(self, field):
        choices = field.choices[1:]  # Exclude the first element
        return field.data or random.choice(choices)[0]

npcgen/characters/views.py
import json
import os

from celery import shared_task
from flask import (
    Blueprint,
    flash,
    redirect,
    render_template,
    request,
    session,
    url_for,
)

from ..auth.decorators import login_required
from ..extensions import db
from .daos import CharacterDao, ItemDao, SkillDao
from .forms import CharacterForm
from .services import CharacterGeneratorService, CharacterTemplateService

bp = Blueprint("characters", __name__)

character_dao = CharacterDao(db.session)
item_dao = ItemDao(db.session)
skill_dao = SkillDao(db.session)

character_generator_service = CharacterGeneratorService(character_dao)
character_template_service = CharacterTemplateService(
    character_dao, item_dao, skill_dao
)


@bp.app_template_filter()
def delta(num):
    return f"+{num}" if not num or num > 0 else num


@bp.app_template_filter()
def character_description(character):
    class_name = character.class_name if character.class_name != "None" else ""
    return (
        f"Level {character.level} {character.race_name} {class_name}".strip()
        + ", "
        f"{character.alignment_name} alignment"
    )


@bp.route("/")
def index():
    return redirect(url_for("characters.generate"))


@bp.route("/characters")
@login_required
def characters():
    user_id = session["user_id"]
    page = int(request.args.get("page") or 1)
    tab = request.args.get("tab") or None
    search = request.args.get("search")
    sort = request.args.get("sort") or "date_desc"

    res = character_dao.get_characters_by_user(
        user_id,
        _resolve_template_filter(tab),
        page,
        search=search,
        sort_field="name" if sort.startswith("name") else "created_at",
        sort_desc=sort.endswith("desc"),
    )

    return render_template(
        "characters/index.html",
        tab=tab,
        sort=sort,
        search=search,
        data=res.data,
        pagination=res.pagination,
    )


def _resolve_template_filter(tab):
    if tab == "templates":
        return True
    elif tab == "my_characters":
        return False
    else:
        return None


@bp.route("/character/<int:character_id>")
@login_required
def character_details(character_id):
    character = character_dao.get_character(
        character_id, populate_items=True, populate_skills=True
    )

    if character is None:
        return "Character not found", 404

    if not character.is_template and character.user_id != session["user_id"]:
        return "Unauthorized", 401

    return render_template(
        "characters/details.html",
        character=character,
    )


@bp.route("/character/delete/<int:character_id>", methods=["POST"])
@login_required
def delete_character(character_id):
    character = character_dao.get_character(character_id)

    if character is None:
        return "Character not found", 404

    if character.is_template:
        return "Bad request", 400

    if character.user_id != session["user_id"]:
        return "Unauthorized", 401

    character_dao.soft_delete_character(character.id)
    flash(f"Character {character.name} deleted", "success")
    return redirect(url_for("characters.characters", _anchor="character"))


@bp.route("/generate", methods=["GET", "POST"])
@login_required
def generate():
    form = _init_character_form()
    user_id = session["user_id"]

    if (
        request.method == "POST"
        and request.headers.get("X-Requested-With") != "XMLHttpRequest"
    ):
        flash("Please enable javascript to generate a character", "danger")
        return redirect(url_for("characters.generate"))

    if form.validate_on_submit():
        task = generate_character.delay(
            {
                "template_id": form.get_choice_or_random(form.template_id),
                "alignment_id": form.get_choice_or_random(form.alignment_id),
                "class_id": form.get_choice_or_random(form.class_id),
                "race_id": form.get_choice_or_random(form.race_id),
                "hints": form.hints.data,
                "user_id": user_id,
            }
        )

        return {"task_id": task.id}

    character_id = request.args.get("character_id")

    if character_id:
        if not character_id.isdigit():
            return "Bad request", 400

        character = character_dao.get_character(
            character_id, populate_items=True, populate_skills=True
        )
        if character is None:
            return "Character not found", 404

        if character.user_id != user_id:
            return "Unauthorized", 401

        return render_template(
            "characters/generate.html", form=form, character=character
        )

    return render_template("characters/generate.html", form=form)


@bp.route("/generate/<task_id>")
@login_required
def generate_status(task_id):
    task = generate_character.AsyncResult(task_id)
    return {
        "ready": task.ready(),
        "successful": task.successful(),
        "value": task.result if task.ready() else None,
    }


def _get_field_choices(options):
    choices = [(opt.id, opt.name) for opt in options]
    choices.insert(0, ("", "Random"))

    return choices


def _init_character_form():
    form = CharacterForm()

    races = character_dao.get_character_race_options()
    form.race_id.choices = _get_field_choices(races)

    classes = character_dao.get_character_class_options()
    form.class_id.choices = _get_field_choices(classes)

    alignments = character_dao.get_character_alignment_options()
    form.alignment_id.choices = _get_field_choices(alignments)

    templates = character_dao.get_character_template_options()
    form.template_id.choices = _get_field_choices(templates)

    return form


# CLI Commands


@bp.cli.command("init-templates")
def init_templates():
    file_path = os.path.join("data", "character_templates.json")

    with open(file_path, "r") as file:
        characters_data = json.load(file)

        for character_data in characters_data:
            character_template_service.create_template(character_data)


# Celery Tasks


@shared_task
def generate_character(options):
    character_id = character_generator_service.generate_character(**options)
    return character_id

npcgen/templates/characters/details.html
{% extends "layout.html" %}
{% block title %}
    {{ character.name }}
{% endblock title %}
{% block content %}
    <div class="container is-max-desktop">
        <div class="columns is-centered">
            <div class="column is-two-thirds">
                {% include "characters/partials/character_details.html" %}
                {% if not character.is_template %}
                    <div class="box">
                        <h2 class="title mb-4 is-4">Delete character</h2>
                        <div class="content">
                            <form action="{{ url_for('characters.delete_character', character_id=character.id) }}"
                                  method="post">
                                <div class="field">
                                    <div class="control">
                                        <label class="checkbox">
                                            <input type="checkbox" name="confirm" required />
                                            Yes, I want to delete this character.
                                        </label>
                                    </div>
                                </div>
                                <button class="button is-danger mt-2" type="submit">Delete</button>
                            </form>
                        </div>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock content %}

npcgen/templates/characters/generate.html
{% extends "layout.html" %}
{% block title %}
    Generate an NPC
{% endblock title %}
{% block content %}
    <div class="container">
        <div class="columns is-variable is-7">
            <div class="column is-one-third">
                <div class="box p-5">{% include "characters/partials/generate_form.html" %}</div>
            </div>
            <div id="character" class="column is-two-thirds">
                {% if character %}
                    {% include "characters/partials/character_details.html" %}
                {% else %}
                    <div class="p-6 is-flex is-align-items-center is-justify-content-center is-fullheight">
                        <div class="is-flex is-align-items-center is-flex-direction-column is-justify-content-center mb-6">
                            <i class="fa-regular fa-eye fa-3x mb-4 has-text-dark-grey"></i>
                            <h1 class="title is-4 has-text-dark-grey has-text-centered mb-1">Your character will show up here</h1>
                            <p class="help has-text-centered">Fill in the form to generate unique NPC characters for your tabletop RPG games.</p>
                        </div>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock content %}
{% block scripts %}
    <script src="{{ url_for('static', filename='js/generate.js') }}"></script>
{% endblock scripts %}

npcgen/templates/characters/index.html
{% extends "layout.html" %}
{% block title %}
    Gallery
{% endblock title %}
{% block content %}
    <div class="container">
        <h1 class="title">Gallery</h1>
        <div>
            <nav class="level">
                <div class="level-left">
                    {% if tab == 'templates' %}
                        <p class="level-item">
                            <a href="{{ url_for('characters.characters', tab='all', sort=sort) }}">All</a>
                        </p>
                        <p class="level-item">
                            <strong>Templates</strong>
                        </p>
                        <p class="level-item">
                            <a href="{{ url_for("characters.characters", tab='my_characters', sort=sort) }}">My characters</a>
                        </p>
                    {% elif tab == 'my_characters' %}
                        <p class="level-item">
                            <a href="{{ url_for('characters.characters', tab='all', sort=sort) }}">All</a>
                        </p>
                        <p class="level-item">
                            <a href="{{ url_for('characters.characters', tab='templates', sort=sort) }}">Templates</a>
                        </p>
                        <p class="level-item">
                            <strong>My characters</strong>
                        </p>
                    {% else %}
                        <p class="level-item">
                            <strong>All</strong>
                        </p>
                        <p class="level-item">
                            <a href="{{ url_for('characters.characters', tab='templates', sort=sort) }}">Templates</a>
                        </p>
                        <p class="level-item">
                            <a href="{{ url_for('characters.characters', tab='my_characters', sort=sort) }}">My characters</a>
                        </p>
                    {% endif %}
                </div>
                <div class="level-right">
                    <div class="level-item">
                        <div class="select">
                            <select onchange="this.options[this.selectedIndex].value && (window.location = this.options[this.selectedIndex].value);">
                                <option value="{{ url_for('characters.characters', tab=tab, search=search, sort='name_asc') }}"
                                        {% if sort == 'name_asc' %}selected{% endif %}>
                                    Sort by Name (Ascending)
                                </option>
                                <option value="{{ url_for('characters.characters', tab=tab, search=search, sort='name_desc') }}"
                                        {% if sort == 'name_desc' %}selected{% endif %}>
                                    Sort by Name (Descending)
                                </option>
                                <option value="{{ url_for('characters.characters', tab=tab, search=search, sort='date_asc') }}"
                                        {% if sort == 'date_asc' %}selected{% endif %}>
                                    Sort by Date (Ascending)
                                </option>
                                <option value="{{ url_for('characters.characters', tab=tab, search=search, sort='date_desc') }}"
                                        {% if sort == 'date_desc' %}selected{% endif %}>
                                    Sort by Date (Descending)
                                </option>
                            </select>
                        </div>
                    </div>
                    <div class="level-item">
                        <form class="field has-addons"
                              action="{{ url_for("characters.characters") }}"
                              method="get">
                            <div class="control">
                                <input class="input"
                                       type="text"
                                       name="search"
                                       placeholder="Search by name"
                                       value="{{ search or '' }}">
                            </div>
                            <div class="control">
                                <button class="button is-info" type="submit">Search</button>
                            </div>
                        </form>
                    </div>
                </div>
            </nav>
            {% if data %}
                <table class="table characters-table is-fullwidth is-hoverable">
                    <thead>
                        <th>Name</th>
                        <th>Description</th>
                    </thead>
                    <tbody>
                        {% for character in data %}
                            <tr>
                                <td>
                                    <a href="{{ url_for('characters.character_details', character_id=character.id) }}">{{ character.name }}</a>
                                </td>
                                <td>{{ character | character_description }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
                <nav class="pagination is-centered"
                     role="navigation"
                     aria-label="pagination">
                    <ul class="pagination-list">
                        {% if pagination.page > 1 %}
                            <li>
                                <a class="pagination-link"
                                   href="{{ url_for('characters.characters', tab=tab, search=search, sort=sort, page=pagination.page-1) }}">Previous</a>
                            </li>
                        {% endif %}
                        {% if pagination.total_pages <= 5 %}
                            {% for p in range(1, pagination.total_pages+1) %}
                                <li>
                                    <a class="pagination-link {% if p == pagination.page %}is-current{% endif %}"
                                       href="{{ url_for('characters.characters', tab=tab, search=search, sort=sort, page=p) }}">{{ p }}</a>
                                </li>
                            {% endfor %}
                        {% else %}
                            {% if pagination.page <= 3 %}
                                {% for p in range(1, 4) %}
                                    <li>
                                        <a class="pagination-link {% if p == pagination.page %}is-current{% endif %}"
                                           href="{{ url_for('characters.characters', tab=tab, search=search, sort=sort, page=p) }}">{{ p }}</a>
                                    </li>
                                {% endfor %}
                                <li>
                                    <span class="pagination-ellipsis">&hellip;</span>
                                </li>
                                <li>
                                    <a class="pagination-link"
                                       href="{{ url_for('characters.characters', tab=tab, search=search, sort=sort, page=pagination.total_pages) }}">{{
                                        pagination.total_pages
                                    }}</a>
                                </li>
                            {% elif pagination.page >= pagination.total_pages - 2 %}
                                <li>
                                    <a class="pagination-link"
                                       href="{{ url_for('characters.characters', tab=tab, search=search, sort=sort, page=1) }}">1</a>
                                </li>
                                <li>
                                    <span class="pagination-ellipsis">&hellip;</span>
                                </li>
                                {% for p in range(pagination.total_pages-2, pagination.total_pages+1) %}
                                    <li>
                                        <a class="pagination-link {% if p == pagination.page %}is-current{% endif %}"
                                           href="{{ url_for('characters.characters', tab=tab, search=search, sort=sort, page=p) }}">{{ p }}</a>
                                    </li>
                                {% endfor %}
                            {% else %}
                                <li>
                                    <a class="pagination-link"
                                       href="{{ url_for('characters.characters', tab=tab, search=search, sort=sort, page=1) }}">1</a>
                                </li>
                                <li>
                                    <span class="pagination-ellipsis">&hellip;</span>
                                </li>
                                {% for p in range(pagination.page-1, pagination.page+2) %}
                                    <li>
                                        <a class="pagination-link {% if p == pagination.page %}is-current{% endif %}"
                                           href="{{ url_for('characters.characters', tab=tab, search=search, sort=sort, page=p) }}">{{ p }}</a>
                                    </li>
                                {% endfor %}
                                <li>
                                    <span class="pagination-ellipsis">&hellip;</span>
                                </li>
                                <li>
                                    <a class="pagination-link"
                                       href="{{ url_for('characters.characters', tab=tab, search=search, sort=sort, page=pagination.total_pages) }}">{{
                                        pagination.total_pages
                                    }}</a>
                                </li>
                            {% endif %}
                        {% endif %}
                        {% if pagination.page < pagination.total_pages %}
                            <li>
                                <a class="pagination-link"
                                   href="{{ url_for('characters.characters', tab=tab, search=search, sort=sort, page=pagination.page+1) }}">Next</a>
                            </li>
                        {% endif %}
                    </ul>
                </nav>
            {% else %}
                <p>No results found.</p>
            {% endif %}
        </div>
    </div>
{% endblock content %}